import Head from 'next/head'
import styles from '../styles/Home.module.css';
import Typewriter from 'typewriter-effect';
import Image from 'next/image';
import Link from 'next/link';

export default function Home() {
  const strings = [
    'Frontend Developer',
    'Cyber security ',
    'Network security Raspberry PI',
    'Ethical hacking',
    'Linux admin'
  ];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='home'>
        <div className='home__title '>
          <h1>Hello, my name is <span>Muhamadaliyev Sherzodbek</span> </h1>
          <div className='home__title-typed'>
            <h3>I'm</h3>
            <h4>
              <Typewriter 
                onInit={(typewriter) => {
                  typewriter
                    .typeString(strings[0])
                    .pauseFor(1000)
                    .deleteAll()
                    .typeString(strings[1])
                    .pauseFor(2000)
                    .deleteAll()
                    .pauseFor(2000)
                    .typeString(strings[2])
                    .pauseFor(2000)
                    .deleteAll()
                    .pauseFor(2000)
                    .typeString(strings[3])
                    .pauseFor(2000)
                    .deleteAll()
                    .pauseFor(2000)
                    .typeString(strings[4])
                    .pauseFor(2000)
                    .deleteAll()
                    .pauseFor(2000)
                    .start();
                }}
                
              />
            </h4>
          </div>
          <div className='home__title-text'>
            <p>I'm a Frontend developer with extensive experience for over 1 years.My expertise is to create and frontend developer,cyber security, and many more...</p>
          </div>
          <div className='home__title-btn'>
            <Link href={'/Sherzodbek.docx'} className={'btn'} download={'CV'}>Download CV</Link>
          </div>

        </div>
        <div className='home__img'>
          <Image src='/men.jpg' width={300} height={100}/>
        </div>

        
      </div>
      
    </div>
  )
}
